### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by coplis** [A03HCY/Netcore#9]
Your project is very interesting and has indeed simplified my development process.

I have tested the library and it throws an exception when receiving data that is too long.
Also, this could potentially risk out of memory as well.

Here is my code

```python
# netcore  ==  0.0.1
# python   ==  3.10.11
# platform ==  windows10

length = 1024 * 1024 * 1024 
sk = socket.socket()
sk.connect(('localhost', 5555))
head = pt.Protocol.make_head('.test', length, 'utf-8')
sk.send(head)
pt.Protocol.stream_until(bytes, length, writefunc=sk.send)
sk.close()
```

And the Error

`protocol, line 368, in __recver
safe = info[1]
IndexError: list index out of range`

**Comment by A03HCY** [comment]
> Your project is very interesting and has indeed simplified my development process.
> 
> I have tested the library and it throws an exception when receiving data that is too long. Also, this could potentially risk out of memory as well.
> 
> Here is my code
> 
> ```python
> # netcore  ==  0.0.1
> # python   ==  3.10.11
> # platform ==  windows10
> 
> length = 1024 * 1024 * 1024 
> sk = socket.socket()
> sk.connect(('localhost', 5555))
> head = pt.Protocol.make_head('.test', length, 'utf-8')
> sk.send(head)
> pt.Protocol.stream_until(bytes, length, writefunc=sk.send)
> sk.close()
> ```
> 
> And the Error
> 
> `protocol, line 368, in __recver safe = info[1] IndexError: list index out of range`

For the error caused by your test, it may be that you are not using safecode()

```python
head = pt.Protocol.make_head('.test'+pt.safecode(), length, 'utf-8')
```

In addition, Package receives data roughly in two steps, the first step is to receive the HEAD information, and the second step is to receive the META.
In the example you gave, you directly consolidate all the information into one send, so that way Package can't handle such a request.

I suggest that both parties to the communication use one class consistently

**Endpoint ( Package )** OR **Protocol**
